version: '3.1'

services:

    db:
        image: postgres:12
        restart: on-failure
        environment:
            POSTGRES_PASSWORD: demo
            POSTGRES_USER: demo
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: on-failure
        ports:
            - 8080:8080