version: '3.1'

services:

    db:
        image: postgres:12
        restart: on-failure
        environment:
            POSTGRES_PASSWORD: demo
            POSTGRES_USER: demo

    adminer:
        image: adminer
        restart: on-failure
        ports:
            - 8080:8080